### ISSUE TITLE
Incompatible with Phaser 3.14.0

### ISSUE THREAD

**Issue by be-bert** [Quinten/phaser3-retina#1]
Thanks for the tutorial.  I was racking my brain as to why this wasn't working in my project.  Seems Phaser 3.14.0 breaks this functionality.  Using `zoom:` in the config file seems to have no effect.  I did notice there is a` resolution:` param that works for things like text and graphics, however images don't seem to be affected, and thus need to be scaled by the `window.devicePixelRatio`.

Any ideas how to solve this with v3.14.0? 

Thanks for your feedback.

EDIT:  Looks like v3.16 is right around the corner with support for HiDPI screens.

**Comment by Quinten** [comment]
I am waiting for 3.16 and the scale manager to update the info in the article/demo...
